### ISSUE TITLE
setup issue dummy dashboard 

### ISSUE THREAD

**Issue by mandevx** [loewexy/pdnsmanager#108]
I thought of taking another dig on pdnsmanager this time with apache2 and php 7.1 installed it and got a setup screen post setup screen it logins to a dummy dashboard without creating a conf of updating it of creating or updating db 
![Screen Shot 2019-06-07 at 4 48 45 PM](https://user-images.githubusercontent.com/5479785/59108952-c48f0700-8944-11e9-97ac-177698794b9a.png)
There is no functionality working on this dashboard as it seems to login without any db and if i logout and login again with any garbage username or password which was never created it logs me  in to same dashboard .

**Comment by bidama** [comment]
same with me.

**Comment by mat1010** [comment]
And also with with me. Were you able to figure this out? Even the upgrading dialog does not come up. I tried todo a fresh install of 2.x and also an upgrade from 1.x. I can't get over the dummy dashboard and don't get any errors. 1.x is working flawless.

**Comment by jussisallinen** [comment]
The same here with php72/73 running on SmartOS, tried also the latest snapshot, the same thing.

**Comment by jussisallinen** [comment]
@loewexy Got time to check this?

**Comment by loewexy** [comment]
I just upgraded my own servers and set up a new server on Ubuntu 18.04 running with PHP 7.2 both of them worked flawless so I have no idea what is going wrong there.

Did you use apache and the configuration from the website?
