### ISSUE TITLE
PTR Records

### ISSUE THREAD

**Issue by ixreiben** [loewexy/pdnsmanager#110]
Hi,

How do I configure a PTR record for this application?
Example;-

test1.example.com 103.29.44.12 A record

the PTR record should be something like; - 44.29.103.in-addr.arpa PTR record
but when i try to add, it becomes ;-

44.29.103.in-addr.arpa.example.com

What would be the correct way to do in this application?

**Comment by loewexy** [comment]
You tried to add a PTR Record to the example.com zone I guess, which is not correct. You will have to create the zone 44.29.103.in-addr.arpa and in that zone you can add then the correct record.
