### ISSUE TITLE
Slow with more domains

### ISSUE THREAD

**Issue by kepi** [loewexy/pdnsmanager#12]
We have about 5k domains and it takes about 8 seconds to load. While domains are loading, I'm not able to enter anything into search box.

I love that PDNS Manager don't have pagination but it would be probably better to use it :) I think if you load like 100 domains first and than use ajax search, it would be much comfortable to use. Of course number of domains to load can be configurable to suits everybody needs.

Thanks for considering.

**Comment by loewexy** [comment]
Do you think it would be enough to set a general limit an how many domains are shown as a result. Others should then be available via search.

I developed PDNS Manager for my own use which is currently about 10 domains :D so i never ran into this issue. I will try to find a fix as soon as I have some time.

**Comment by kepi** [comment]
I think there may be cases when somebody has domains with really similar name (or better with same base). With hard limit without pagination some generic search could return more results than this limit. In such case those domain would be inaccessible.

For us it doesn't matter but I think that pagination is better solution (and harder to implement ofc :)).

**Comment by loewexy** [comment]
Okay this should be a manageable task although. But it can take a little time to implement.

**Comment by kepi** [comment]
I think I just found better solution:

Simply select count of domains and when it is larger than X (i.e. 100) don't print anything (or first 100) until user search term. On search term simply print all found results.

You would probably need to change search from simple javascript to ajax on. but I think its probably easier to implement and IMHO the best because you can avoid pagination at all.

**Comment by mauricemeyer** [comment]
Going to tackle that on my fork, expect a pull request.

**Comment by mauricemeyer** [comment]
@kepi, your last proposal is a good idea, but has one flaw: If you just want to get an overview over your domains, you'd face a very difficult task as you couldn't just display them all. 

I'm probably going to add a "you got more than X domains, sure you want to display them all" warning, but I'm not completely happy with that. Any suggestions?

**Comment by loewexy** [comment]
Maybe it would be good to add paging to the results. If your search is specific enough you would not see it but otherwise you can just go through the pages. Maybe the number of records on one page could be configurable in the config-user.php

**Comment by kepi** [comment]
If we can avoid pagination, it would be amazing. I simply hate it but sometime its necessary evil.

For me, button "Display all domains" in case search term is not filled yet is good enough option and better than pagination.

I have previously one more idea - to simply leave domains as they are now and implement #13 alongside with creating new landing page with search input only (or some fancy dashboard). In such case user can use search box to go to any domain, can login fast and still can display all domains (and wouldn't mind wait a little because he want them all).
