### ISSUE TITLE
Problem with PTR and SLAVE zone

### ISSUE THREAD

**Issue by Moglius** [loewexy/pdnsmanager#120]
Hello, I've a problem when import a reverse slave zone. In my database the record is fine, showing the name like this:

![image](https://user-images.githubusercontent.com/290992/74143611-e2022800-4bd9-11ea-9e99-e8086e2ce154.png)

But in the web GUI of PDNS Manager, i may not see the first octect:

![image](https://user-images.githubusercontent.com/290992/74143712-14138a00-4bda-11ea-9e33-e5f2723bcb5b.png)

if i put the record mannualy, next i see well the record in the web GUI and in the database the record change the string "in-addr.arpa" to this: "IN-ADDR.ARPA":

1- Putting Manually:
![image](https://user-images.githubusercontent.com/290992/74143836-49b87300-4bda-11ea-9092-00fd80470f66.png)
2- record save:
![image](https://user-images.githubusercontent.com/290992/74143863-589f2580-4bda-11ea-933f-b45fe05fef27.png)
3- database change:
![image](https://user-images.githubusercontent.com/290992/74144043-c0557080-4bda-11ea-83cd-4fb6c62c74d8.png)
4-After the change, the web gui showing fine the record:
![image](https://user-images.githubusercontent.com/290992/74144355-5a1d1d80-4bdb-11ea-94a6-25a18904f11d.png)

the DNS resolution works fine before the change in web gui and continue working after the change. Thanks in advance!!

**Comment by loewexy** [comment]
What does the domain Entry for domain 41 look like?

**Comment by Moglius** [comment]
I had to use another domain id because i updated the records to uppercase and the problem disapear. Now i use the domain id 848 that i recently added as slave zone, and the problem persist:

1- Database view:
mysql> select * from domains where id = 848;
+-----+-------------------------+------------+------------+-------+-----------------+---------+
| id  | name                    | master     | last_check | type  | notified_serial | account |
+-----+-------------------------+------------+------------+-------+-----------------+---------+
| 848 | 131.141.10.IN-ADDR.ARPA | 10.1.1.10  | 1581338463 | SLAVE |            NULL | NULL    |
+-----+-------------------------+------------+------------+-------+-----------------+---------+
1 row in set (0.00 sec)

mysql> select * from records  where id = 18867;
+-------+-----------+----------------------------+------+------------------------------------+------+------+-------------+----------+-----------+------+
| id    | domain_id | name                       | type | content                            | ttl  | prio | change_date | disabled | ordername | auth |
+-------+-----------+----------------------------+------+------------------------------------+------+------+-------------+----------+-----------+------+
| 18867 |       848 | 62.131.141.10.in-addr.arpa | PTR  | GBA-Ferro-Maipu.routers.gba.gov.ar |  600 |    0 |        NULL |        0 | NULL      |    1 |
+-------+-----------+----------------------------+------+------------------------------------+------+------+-------------+----------+-----------+------+
1 row in set (0.00 sec)

2- WebGUI view:
![image](https://user-images.githubusercontent.com/290992/74151093-2ac1dd00-4bea-11ea-9851-a74474732a1d.png)

Thanks!!

**Comment by loewexy** [comment]
I fear that this is due the missmatch of in-ddr.arpa to IN-ADDR.ARPA. But if you add the records via the GUI this should get added in a consistent way...

**Comment by Moglius** [comment]
Yes, that you says. I've only problems with reverse zones in a migration scenario. I changed to uppercase and its works. Thanks @loewexy!!

**Comment by loewexy** [comment]
So does this solve your request?

**Comment by Moglius** [comment]
Yea, thanks!!
