### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by axiades** [loewexy/pdnsmanager#122]
Hey i have a Problem..

on a New Debian LXC with Apache2 PHP7.4.

i Can´t install PDNS Manager.

"Request failed with status code 403"

Please help

**Comment by R0Wi** [comment]
@axiades could you provide additional information on this, please?

- When do you get the `403` error (on which request)?
- Can you see anything in apache logs under `/var/log/apache2/error.log`? Maybe you could post a snippet here?
- Can you provide the dev-console output of your browser and maybe a screenshot of the network-tab?
- Did you properly setup the apache virtualhost files like described [here](https://pdnsmanager.org/quickstart/)? 
- Are you able to access your webroot generally?
