### ISSUE TITLE
Error while upgrading DB.

### ISSUE THREAD

**Issue by kalkir** [loewexy/pdnsmanager#123]
I have recently upgraded pdns manager to new version. but when upgrading database I am getting following error:
================
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`powerDNS`.`#sql-799_5b03`, CONSTRAINT `records_ibfk_1` FOREIGN KEY (`domain_id`) REFERENCES `domains` (`id`) ON DELETE CASCADE)

**Comment by R0Wi** [comment]
Could you please tell from which version you upgraded? And which version was the target?

**Comment by kalkir** [comment]
Thanks for the udate, I have fixed by manully run the queries in mysql.
Error seems to be due to existance of some tables and constrains. It will
be helpful to skip this in upgrade script in future versions(in database
upgrade).

**Comment by kalkir** [comment]
By the way, version that I have tried to upgrade was 1.21 and to version 2
