### ISSUE TITLE
Support LUA Records

### ISSUE THREAD

**Issue by brlumen** [loewexy/pdnsmanager#124]
Is there any [LUA Records](https://doc.powerdns.com/authoritative/lua-records/index.html#lua-records) support for the PowerDns Authority server? Are you planning?

**Comment by w796933** [comment]
powerdns  4.2  support    LUA  records  . how  to  support   lua  recores ?

**Comment by loewexy** [comment]
There is currently no support but I would welcome a pull request. Here are some hints on how to achive that:

https://github.com/loewexy/pdnsmanager/blob/master/frontend/src/app/services/state.service.ts
This is the definition of the allowed Types in the Frontend.

https://github.com/loewexy/pdnsmanager/blob/master/backend/src/config/ConfigDefault.php
Here it is for the backend.

I imagine adding it in both locations would suffice for basic support. I do not know if a LUA Record can easily be typed into a one line input field. It there is something else required it would probably be more complex.

**Comment by w796933** [comment]
i  tsc  no pass .   sir ,  you can  update  new   version support  LUA ？  so thanks .

**Comment by loewexy** [comment]
This should work now in the current development version. So please try this.
