### ISSUE TITLE
How do I reset password via the database?

### ISSUE THREAD

**Issue by wioxjk** [loewexy/pdnsmanager#126]
How to I change the password of an admin-user?
What kind of hash is being used for the password?

**Comment by loewexy** [comment]
PDNSManager uses PHPs password_hash() function. You can create a new password from the PHP Cli.

**Comment by wioxjk** [comment]
Thanks!
Would you mind to quickly share how that is done practically? :)

**Comment by loewexy** [comment]
Open php in interactive mode using `php -a` then enter
```php
echo password_hash('test', PASSWORD_DEFAULT);
```

**Comment by wioxjk** [comment]
Forgot to say thanks!
Would be awesome if this could be added to your wiki so people does not have to take your time on issues like this in the future :)

Thanks!
Feel free to close this issue
