### ISSUE TITLE
Password manager: button "Login" disabled

### ISSUE THREAD

**Issue by simmstein** [loewexy/pdnsmanager#127]
Hello, 

When I use my password manager to fill the login form, I can't submit because the button "Login" is still disabled. I have to add and remove a char in each field to enabled the button "Login".

Video: http://kim.neutralnetwork.org/~simon/github/pdns-login-issue.mp4

**Comment by loewexy** [comment]
Which password manager are you using? That seems to be a bug of that software since it does not set the modified flag for the login field.

**Comment by simmstein** [comment]
I use https://addons.mozilla.org/fr/firefox/addon/nextcloud-passwords/

**Comment by loewexy** [comment]
I guess you should file the Bug there https://github.com/marius-wieschollek/passwords-webextension

**Comment by simmstein** [comment]
According to this code https://github.com/marius-wieschollek/passwords-webextension/blob/master/src/js/Controller/Client/FillPassword.js#L42 I think that all required events are triggered when fields are filled.
That seems to be an issue with angular and autofill: https://stackoverflow.com/questions/41932810/angular-2-and-browser-autofill

**Comment by loewexy** [comment]
I myself use KeepassXC and the browser Plugin for that and this works without problem.

**Comment by simmstein** [comment]
It's fixed from the password manager.
