### ISSUE TITLE
PDNS manager LDAP configuration not working

### ISSUE THREAD

**Issue by kalkir** [loewexy/pdnsmanager#131]
I have added following LDAP configuration in ConfigUser.php

$config['auth_type'] = 'ldap';
$config['ldap_uri'] = '';
$config['ldap_bind_dn'] = '';
$config['ldap_bind_pw'] = '';
$config['ldap_base_dn'] = '';
$config['ldap_search'] = '(&(uid=%user%)()';

but still panel accepting db authentication and ldap users failed to login, please correct me if I did anything wrong.

**Comment by loewexy** [comment]
PDNS Manager does not support LDAP authentication.
