### ISSUE TITLE
Install - fails

### ISSUE THREAD

**Issue by abtme** [loewexy/pdnsmanager#136]
Hi

I have tried Debian 10(default PHP 7.3.x) and Ubuntu 18.04 (default PHP 7.2.x)

Both installation have been on brand new installs. both do not not create any Mysql tables (should they - documentation is not clear)

No errors I can find.

Let me know what information you need - as I really would like to use your software.

Thanks

Andrew

**Comment by loewexy** [comment]
Did you follow exactly the instructions on the website. What happens after you hit `Setup` in the Setup-Wizzard. Helpful would be the Apache access and error log.

**Comment by abtme** [comment]
Hi 

Thanks for getting back to me.

I setup mysql with a database and password - so its ready to go.
Apache setup as per your documentation with php-json and pecl install for acpu

root@ubuntu18-test:/var/www/powerdns/backend/config# php -m | grep json
json
root@ubuntu18-test:/var/www/powerdns/backend/config# php -m | grep apcu
apcu
root@ubuntu18-test:/var/www/powerdns/backend/config#

fqdn\setup - I fill in the details and it then returns to the login prompt.

no apache errors in the log

but no tables are created during the setup phase.
also I am able to login with any credentials.

Andrew

**Comment by abtme** [comment]
here are the logs from apache
[apache.log](https://github.com/loewexy/pdnsmanager/files/5764184/apache.log)

**Comment by loewexy** [comment]
I guess there is some configuration error in your apache config. Since the call to `/api/v1/setup` returns HTTP Code 200 which is not a code that is returned by the API for that endpoint. So my guess is that pdnsmanager is not called but instead some arbitrary response from the server is received.

What do you get if you visit `https://example.com/api/v1/remote/servertime`?

**Comment by abtme** [comment]
```
10.68.31.73 - - [04/Jan/2021:10:49:12 +0000] "GET /app/v1/remote/servertime? HTTP/1.1" 200 689 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
```

this is the apache config used.
```
root@ubuntu18-test:/var/www/powerdns/backend/config# cat /etc/apache2/sites-enabled/pdns.conf
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName testpdns.gosport.local

    DocumentRoot /var/www/powerdns/frontend

    RewriteEngine On
    RewriteRule ^index\.html$ - [L]
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
    RewriteRule !^/api/\.* /index.html [L]

    Alias /api /var/www/powerdns/backend/public
    <Directory /var/www/powerdns/backend/public>
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^ index.php [QSA,L]
    </Directory>
  CustomLog /var/log/apache2/testpdns.gosport.local-access.log combined
  ErrorLog /var/log/apache2/testpdns.gosport.local-error.log
</VirtualHost>
```

**Comment by loewexy** [comment]
> ```
> 10.68.31.73 - - [04/Jan/2021:10:49:12 +0000] "GET /app/v1/remote/servertime? HTTP/1.1" 200 689 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
>```

I am interested what you see in your browser, not in the log this time.

Your config looks sane, is there something in your error log?

**Comment by abtme** [comment]
Before I press enter

![before](https://user-images.githubusercontent.com/73382620/103528407-d071e080-4e7b-11eb-8653-33bc0c774319.PNG)

After I pressed enter.

![after](https://user-images.githubusercontent.com/73382620/103528404-cfd94a00-4e7b-11eb-947a-bd7e7509e6f4.PNG)


error log is empty.

**Comment by abtme** [comment]
the first picture is after
the second picture is before.

**Comment by loewexy** [comment]
That seems to be that the rewrite does not work. Do you have mod_rewrite enabled in apache?

**Comment by abtme** [comment]
Yes - apache would not start until it was enabled.

```
root@ubuntu18-test:/var/www/powerdns/backend/config# apachectl -M
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_event_module (shared)
 negotiation_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 status_module (shared)
root@ubuntu18-test:/var/www/powerdns/backend/config# apachectl -M | grep rewr
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
 rewrite_module (shared)
root@ubuntu18-test:/var/www/powerdns/backend/config#
```

**Comment by loewexy** [comment]
Then I really have no clue on what is going wrong for you. But the call to `https://example.com/api/v1/remote/servertime` should return you a JSON document with a Unix timestamp. It seems that either the Alias or rewriting does not work for you... But I do not know why. For me a fresh installation on Ubuntu 18.04 with the website tutorial does work without problems.

**Comment by abtme** [comment]
Ok - will try and debug the rewrite - thank you for the help - at least I now know im not going mad. !!

**Comment by abtme** [comment]
Also
- can you tell me - before I install pdnsmanager do you expect there to be a working pdns mysql installation ?

**Comment by abtme** [comment]
I did a curl 
```
root@debian-dev01:~# curl http://testpdns.gosport.local/app/v1/remote/servertime
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>PDNS Manager</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles.38d51718cb6869288f32.css"></head>

<body>
  <app-root></app-root>
<script type="text/javascript" src="runtime.a66f828dca56eeb90e02.js"></script><script type="text/javascript" src="polyfills.001f1812942338ddb405.js"></script><script type="text/javascript" src="main.461bd5e9e32973318e39.js"></script></body>
```
and got this response from the webserver.

```
==> /var/log/apache2/testpdns.gosport.local-error.log <==
[Mon Jan 04 11:32:32.856779 2021] [rewrite:trace2] [pid 2990:tid 140129163253504] mod_rewrite.c(482): [client 172.31.99.11:33626] 172.31.99.11 - - [testpdns.gosport.local/sid#7f727a1f6880][rid#7f727a13a0a0/initial] init rewrite engine with requested uri /app/v1/remote/servertime
[Mon Jan 04 11:32:32.856852 2021] [rewrite:trace3] [pid 2990:tid 140129163253504] mod_rewrite.c(482): [client 172.31.99.11:33626] 172.31.99.11 - - [testpdns.gosport.local/sid#7f727a1f6880][rid#7f727a13a0a0/initial] applying pattern '^index\\.html$' to uri '/app/v1/remote/servertime'
[Mon Jan 04 11:32:32.856871 2021] [rewrite:trace3] [pid 2990:tid 140129163253504] mod_rewrite.c(482): [client 172.31.99.11:33626] 172.31.99.11 - - [testpdns.gosport.local/sid#7f727a1f6880][rid#7f727a13a0a0/initial] applying pattern '^/api/\\.*' to uri '/app/v1/remote/servertime'
[Mon Jan 04 11:32:32.856900 2021] [rewrite:trace2] [pid 2990:tid 140129163253504] mod_rewrite.c(482): [client 172.31.99.11:33626] 172.31.99.11 - - [testpdns.gosport.local/sid#7f727a1f6880][rid#7f727a13a0a0/initial] rewrite '/app/v1/remote/servertime' -> '/index.html'
[Mon Jan 04 11:32:32.856917 2021] [rewrite:trace2] [pid 2990:tid 140129163253504] mod_rewrite.c(482): [client 172.31.99.11:33626] 172.31.99.11 - - [testpdns.gosport.local/sid#7f727a1f6880][rid#7f727a13a0a0/initial] local path result: /index.html
[Mon Jan 04 11:32:32.856935 2021] [rewrite:trace2] [pid 2990:tid 140129163253504] mod_rewrite.c(482): [client 172.31.99.11:33626] 172.31.99.11 - - [testpdns.gosport.local/sid#7f727a1f6880][rid#7f727a13a0a0/initial] prefixed with document_root to /var/www/powerdns/frontend/index.html
[Mon Jan 04 11:32:32.856950 2021] [rewrite:trace1] [pid 2990:tid 140129163253504] mod_rewrite.c(482): [client 172.31.99.11:33626] 172.31.99.11 - - [testpdns.gosport.local/sid#7f727a1f6880][rid#7f727a13a0a0/initial] go-ahead with /var/www/powerdns/frontend/index.html [OK]

==> /var/log/apache2/testpdns.gosport.local-access.log <==
172.31.99.11 - - [04/Jan/2021:11:32:32 +0000] "GET /app/v1/remote/servertime HTTP/1.1" 200 848 "-" "curl/7.64.0"
```

**Comment by loewexy** [comment]
Please use codeblocks so that your answer is readable.

Your URL for curl is wrong and therefore everything else does not work. You should habe `/api` not `/app`

**Comment by abtme** [comment]
ok - my fault 

somehow missed the installation of php for apache2, and this created the tables in my database along with an entry for the admin user I setup.

however when I login I see

![missing-menu](https://user-images.githubusercontent.com/73382620/103532736-ac1a0200-4e83-11eb-96c8-94bf74870497.PNG)

api now works - sorry about that.

![api](https://user-images.githubusercontent.com/73382620/103532842-dbc90a00-4e83-11eb-93a3-9f38b165856e.PNG)

**Comment by loewexy** [comment]
Go to the developer console an check the requests made for errors.

**Comment by abtme** [comment]
I dont know how to do that 

but do you mean F12 in the browser and check "console"

if so 

this is all I see


![console error](https://user-images.githubusercontent.com/73382620/103533343-da4c1180-4e84-11eb-82f5-89bf72d19403.PNG)

**Comment by loewexy** [comment]
Yeah but you need to go to the network tab.

**Comment by abtme** [comment]
Dont know what im loooking for

do you want me to post what I see ?

**Comment by loewexy** [comment]
Yes open that tab then do a fresh login. All HTTP calls done by the application should be there.

**Comment by abtme** [comment]
I dont see any errors

**Comment by loewexy** [comment]
Can you post a screenshot of them?

**Comment by abtme** [comment]
I got it working on Debian - by adding apache2 php and php-dev and libmodphp
did the same on ubuntu

**Comment by abtme** [comment]
also looking at the contents of the data on network - it had credentials in it, especially the session data.

suspect its because the http not https
