### ISSUE TITLE
Move or clone add inputs to top of page

### ISSUE THREAD

**Issue by kepi** [loewexy/pdnsmanager#14]
Inputs for adding new record are at bottom of the page when editing zone.

With small zones its ok but if you have hundreds of records in one zone, it isn't comfortable to scroll down every time you want to add something.

Move the element to top is probably not best option. Cloning it so you can add new record from top and also from bottom would be probably better.

**Comment by loewexy** [comment]
Okay yes, i can understand this issue. Moving to the top would indeed be very easy. I try to get it to work duplicated.

**Comment by loewexy** [comment]
Doublicating would be possible with the 2.0 architecture but I do not like the look an layout. But with paging support the add inputs are not that low.
