### ISSUE TITLE
MySQLi Exception causing 500 on api/domains.php (SQL92 compatibility issue)

### ISSUE THREAD

**Issue by alexdo** [loewexy/pdnsmanager#15]
I installed pdnsmanager on top of an existing PowerDNS + Poweradmin setup, looking to replace Poweradmin completely.
However, after install procedure is over, no domains are shown. Creating new zones is possible, they are also inserted into the DB properly, but the domain listing is still empty.

I was able to locate an exception after digging around
```
PHP message: PHP Fatal error:  Uncaught exception 'mysqli_sql_exception' with message 
''[my_db_name].D.name' isn't in GROUP BY' in /var/.../.../pdnsmanager/api/domains.php:66

Stack trace:
#0 /var/.../.../pdnsmanager/api/domains.php(66): mysqli->prepare('?        SELECT...')
#1 {main}
  thrown in /var/.../.../pdnsmanager/api/domains.php on line 66
```

SQL92 requires that all columns (except aggregates) in the select clause is part of the group by clause. SQL99 loosens this restriction a bit and states that all columns in the select clause must be functionally dependent of the group by clause. 
MySQL allows the latter by default, however my sql_mode is set to ONLY_FULL_GROUP_BY to prevent MySQL from returning non-deterministic answers.

Including all columns in fixes this issue.
```diff
--- a/api/domains.php
+++ b/api/domains.php
@@ -35,7 +35,7 @@ if(isset($input->action) && $input->action == "getDomains") {
         LEFT OUTER JOIN records R ON D.id = R.domain_id
         LEFT OUTER JOIN permissions P ON D.id = P.domain
         WHERE (P.user=? OR ?)
-        GROUP BY D.id
+        GROUP BY D.id, D.name, D.type
         HAVING
         (D.name LIKE ? OR ?) AND
         (D.type=? OR ?)
```

I have two suggestions regarding this matter:
* Either ensuring complete group by clauses in aggregating queries
* or checking for ONLY_FULL_GROUP_BY during the installation procedure and issuing a warning if present.

Let me know what you think, I'm happy to help out 😊 

More information on my setup:
My DB Schema: https://gist.github.com/alexdo/94ddfb9223cebfd7edcbd6461d640b5b
MySQL Version: 5.6.28-0ubuntu0.14.04.1-log
PHP Version: PHP 5.5.9-1ubuntu4.16 (Ubuntu 14.04 LTS default)

**Comment by loewexy** [comment]
I think fixing the SQL query would be the nice and clean solution. Can you make a pull request for this fix? Otherwise I will do it, but this can take some days.

**Comment by alexdo** [comment]
Luckily only one query was affected 👍 
PR #16 created.
