### ISSUE TITLE
Let's encrypt does not work

### ISSUE THREAD

**Issue by Sparc0** [loewexy/pdnsmanager#18]
I followed the docs on how to set up let's encrypt signing. I got a error if i named the file config.sh so i hade to rename it to just **config**.

But when i try to sign i get **Id and domain do not match!**

In the pdns-acme.json file i have the domain i want to sign and the same ID as the "ACME" key has on the _acme record.

**Comment by loewexy** [comment]
The filename was changed in a newer version of letsencrypt.sh, I updated the config accordingly.

Have you used _acme-challenge.example.com as domain or only example.com? You have to use it without _acme-challenge as domain but the ID from the key added to the _acme-callenge. record.

If this does not work maybe you can provide your config file eigther with tld changed to example.com or via Email only to me.

**Comment by Sparc0** [comment]
**pdns-acme.json**
`{
    "config": {
        "server": "https://powerdns.example.se/",
        "pdns-client": "../pdns-client/pdns-client",
        "deploy-wait": 300
    },
    "domains": {
        "example.se": {
            "id": 2,
            "hook": "echo Restarting service for example.com"
        }
   }
}`
**domains.txt**
`example.se`

I added the public key to `_acme-challenge.example.se` and i try to sign a cert for example.se

This command works:
 ./pdns-client -s https://powerdns.example.se/ -d _acme-challenge.example.se -i 2 -c none

**Comment by loewexy** [comment]
Okay this seems a little strange as your config seems valid. Also that pdns-client works is a good sign.

Can you change to the pdns-acme directory and run
`./pdns-acme deploy_challenge example.se foo test`
and check if the _acme-challenge.example.se txt record gets the content test.

**Comment by Sparc0** [comment]
I get: `Id and domain do not match!`

**Comment by loewexy** [comment]
Okay you get the same error here. Can you execute
`bash -x pdns-acme deploy_challenge example.se foo test`
and supply the output? This is the detailed log of the execution.

**Comment by Sparc0** [comment]
I sent you a email. Did not bother to replace TLD.
