### ISSUE TITLE
"No such file or directory" on installation

### ISSUE THREAD

**Issue by Yamakasi** [loewexy/pdnsmanager#23]
When I run http://mydomain/install.php and I hit install I get:

No such file or directory

Is this known as there is no PHP-error shown it's Jquery.

Thanks!

**Comment by loewexy** [comment]
Are you shure that you have copied the complete folder and not only install.php?

If so, can you please supply a log of the requests done to the server. You can export this e.g. from the developer options of firefox.

**Comment by Yamakasi** [comment]
Yes all files are copied.

I just see a post and that is about it, need to check what I see more.

**Comment by Yamakasi** [comment]
OK  I checked and I only see thr JSON post and that's it... all info is there, I'm not sure where it goes wrong.

On the stable version, this is master, I got this with mysqli enabled:

PHP Fatal error:  Call to a member function bind_param() on a non-object in /var/www/html/api/install.php on line 126

**Comment by loewexy** [comment]
What is the HTTP return code of the POST request?

You should probably use the stable version. But current stable 1.2.1 should currently be the same as master.

What is you Operating System, and which versions of PHP and MySQL do you use?

**Comment by Yamakasi** [comment]
I just get back this:

{"status":"error","message":"No such file or directory"}

PHP 5.5.9-1ubuntu4.19 (cli) (built: Jul 28 2016 19:31:33)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3

**Comment by loewexy** [comment]
This seems to be a problem with your setup of mysql. Have you moved the location of the mysql socket? Then you should also reflect this change in the php config.

You can also try not to use localhost as Hostname but 127.0.0.1 to force php to use a tcp connection instead of unix domain.

**Comment by Yamakasi** [comment]
It's just a working setup where I used dnsshop before, this used localhost also.

I have apt-get upgrade the whole box and now get again:

 PHP Fatal error:  Call to a member function bind_param() on a non-object in /var/www/html/api/install.php on line 126,

Same issue happens with 127.0.0.1

**Comment by loewexy** [comment]
Are you familiar with PHP?

You can add an additional debug output on api/install.php at line 117. This is the place where I assume your error occurs, as this is the only place an error message is added to the result JSON.

In line 113 is the initialization of the MySQL connection, which uses the parameters  supplied in the POST reqest.

**Comment by Yamakasi** [comment]
OK, my fault it was a create permssion error for tables.

It might be nice to add such rights check.
