### ISSUE TITLE
Update Documention - Requirements

### ISSUE THREAD

**Issue by techteam-bln** [loewexy/pdnsmanager#25]
It seems, that the pdnsmager needs a php version >= 5.5 and not 5.x

I tried to install it on an centos 7.2 which only has an php 5.4.x and it fails on install.php  line 120 password_hash(), which is a new function of php 5.5

**Comment by loewexy** [comment]
You are right. I think this bugreport affects only the website. I will fix it in that repo. If I am mistaken and there is also wrong documentation in this repo, please correct me.
