### ISSUE TITLE
Feature List

### ISSUE THREAD

**Issue by Upgreydd** [loewexy/pdnsmanager#26]
Hey. PDNS Manager is very nice, but I've found some feature's that would be nice:
1. API Key per user - that would be nice to bond user with api key - then feature two would be simplest.
2. Delegate selected records from domain for selected user - in this case User using apikey could change this record value.
3. TXT and few others records should be a textarea not input.

**Comment by loewexy** [comment]
1+2 would be a significant change, for which I dont have enough time at the moment. Also a consistent concept for that must be developed.

For Number 3. is there a situation where this would be usefull?

p.s. try to make different points with different issues, so they can be handled separately.

**Comment by lamclennan** [comment]
With 2. you could create a separate zone and for the records and delegate it with some NS records.
