### ISSUE TITLE
Trimming VARCHAR records

### ISSUE THREAD

**Issue by dmarkic** [loewexy/pdnsmanager#27]
Hello,

You should trim the values that go into database (for VARCHAR/CHAR fields) before inserting/updating.
For instance: 
in the api/edit-master.php file in action for save and insert, you should trim the $input->content variable before storing, as powerdns has some issues with AXFR, if record has space/tabs after the content. Eg: storing "my.cname.example.org  " in content field of records table, will cause it to fail the AXFR with error: 
Exception: All data was not consumed
Please correct this in your next version.

Kind regards,
Dejan

**Comment by loewexy** [comment]
Yes, this definitely is a good idea. I currently have not enough time to work on it. If you want to make a Pull-Request feel free to do so. Otherwise it will take some time.

**Comment by lamclennan** [comment]
Done: https://github.com/loewexy/pdnsmanager/commit/5d5f8c4af75e7680cfa43d053ba7e85645b8d287
