### ISSUE TITLE
DynDNS Idea

### ISSUE THREAD

**Issue by psi-4ward** [loewexy/pdnsmanager#30]
Its possible to use the remote API for DynDNS like 
`https://pdns.example.com/api/remote.php?action=updateRecord&domain=home.example.com&id=1&password=secret&content=123.123.123.123`
but its difficult to configure, especially setting the IP.

What about an `api/dyndns.php` endpoint?
* Validation with simple token
* Content (IP) from `$_SERVER['REMOTE_ADDR']`?

So I could configure in my <whatever>Box `https://pdns.example.com/api/dyndns.php?token=asd` and I'm ready?

**Comment by TheFatherMind** [comment]
I currently have a dynamic DNS working with mine using a windows client we programmed and some front end code to update the database.   We have a linux script you can cron somewhere.  But I have not seen it in a while so we may have to remake that.  We are working on integrating the database key into the GUI of PDNS Manager.  Once I have enough to work with I will post a thread with all source code.  Should not be much longer.  Just waiting on one of my programmers to finish up some priority stuff.

**Comment by mauricemeyer** [comment]
As the API will be completely reworked for 2.0, I will close this issue.
An endpoint using the REMOTE_ADDR is planned for this, too to make DynDNS updates easier.
