### ISSUE TITLE
Connection to database failed.

### ISSUE THREAD

**Issue by Bram-Zijp** [loewexy/pdnsmanager#32]
When you follow all instructions as written on your website I end up with this error. Connection to database failed. Upon visiting http://example.com/index.php

When I setup my database details in /var/www/pdnsmanager/config/config-default.php  the error is gone.

**Comment by loewexy** [comment]
This should not happen. Did you use the installation assistant? Can you provide some more information on your environment?

**Comment by Bram-Zijp** [comment]
@loewexy 
Ubuntu 16.04
PHP7.0
NGINX
MariaDB 10.1


Yes I used the installation assistant, and after using the config-default.php work around I found that I did create 4 admin users in the process of redoing the install script.

**Comment by loewexy** [comment]
Maybe check if the php user has write permissions in the config directory.

**Comment by Bram-Zijp** [comment]
@loewexy 
This was indeed the problem. Thanks.
chown -R www-data:www-data /var/www/pdnsmanager
