### ISSUE TITLE
Cannot login anymore after upgrade to latest version

### ISSUE THREAD

**Issue by Yamakasi** [loewexy/pdnsmanager#36]
I have updated to the latest version, the DB is migrated, but I cannot login anymore to my account.

No errors shown, only "Username and/or password wrong!"

**Comment by loewexy** [comment]
To which version did you update? Git or v1.2.1?

**Comment by Yamakasi** [comment]
It was the GIT Master branche but I found the problem.

It seems that the user tables became users and also that the domain type needs to be MASTER instead of master before you can edit them.
