### ISSUE TITLE
Master server not added to Domain record

### ISSUE THREAD

**Issue by Yamakasi** [loewexy/pdnsmanager#37]
It's still not possible to add the master IP to the domain record when a domain is added. Is this not needed for a properly working PowerDNS setup ?

**Comment by loewexy** [comment]
I do not understand what you think is wrong here. Can you give steps to reproduce your problem and what happens and what should happen?

**Comment by Yamakasi** [comment]
There is a column in the domains table which is named "master". When you add a domain there should be added the IP of the master as far I I know.

**Comment by loewexy** [comment]
That is only required for slave zones. In every other case it would be the server itself. Do you have or problem and something is not working?

**Comment by Yamakasi** [comment]
I'm checking out the best way to replicate/sync to slave servers, or actually secondary and more dns servers. I assumed the master ip was needed there.

**Comment by loewexy** [comment]
It is for slave zones. Which is currently not supported by pdnsmanager.

**Comment by Yamakasi** [comment]
What is so difficult here ? As far as I know powerdns has it's own mechanism to push it's changes to a slave. I mean, do you run a single DNS server ? I doubt it.

**Comment by loewexy** [comment]
Yes it has such a mechanism. Yes I personally have only a primary as the secondary is provided by my provider. If slave zones are missing for your functionality you are welcome to implement it and make a pull request.
