### ISSUE TITLE
Nothing happens when install button pressed...

### ISSUE THREAD

**Issue by TheFatherMind** [loewexy/pdnsmanager#41]
I just did a fresh git pull..
Gave full access to the install files chmod a+rwx
fill out the form as indicated.
Press install button.. button presses but nothing happens..
Also.. for fun.. I copied the config-user.php from my working site.. but passwords are not accepted when I try to login.  Also tried adding $config['db_type'] = "mysql"; to the config-user.php and that did not help.

![install screenshot](https://user-images.githubusercontent.com/11869399/28035440-76a7cbc2-6569-11e7-8aeb-e9482514b5c2.png)

**Comment by loewexy** [comment]
Can you open the developer tools an make a protocol of the requests?

**Comment by TheFatherMind** [comment]
Is this what you are after?  I do not understand the steps necessary to make a "protocol of the requests".  I am a tech with some programming skills not a web developer.

![console](https://user-images.githubusercontent.com/11869399/28036552-75ac74b2-656d-11e7-8a3f-1476a99fadd4.png)

**Comment by loewexy** [comment]
https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-a-HAR-File-in-Chrome-IE-or-Firefox/ta-p/366 there are some instructions for the commonly used browsers.

**Comment by mauricemeyer** [comment]
@TheFatherMind Please check if the web server is allowd to write to

`/var/web/desktopmasters.com/config`. A common issue is that it isn't, then it can't create the `config-user.php` and silently fails. See also #34.

**Comment by TheFatherMind** [comment]
The php web server service is running as the user that owns the
    folders and files.  It has access to write to everything.
    Although the path you mentioned below does not match my
    configuration scheme.
    For fun I chmod'ed everything to a+w and that did not help ether.
    
    ~ Merlin
    
    On 7/19/2017 12:02 PM, Maurice Meyer
      wrote:
    
    
      @TheFatherMind
        Please check if the web server is allowd to write to
      /var/web/desktopmasters.com/config. A common issue
        is that it isn't, then it can't create the config-user.php
        and silently fails. See also #34.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/loewexy/pdnsmanager","title":"loewexy/pdnsmanager","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/loewexy/pdnsmanager"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mauricemeyer in #41: @TheFatherMind Please check if the web server is allowd to write to\r\n\r\n`/var/web/desktopmasters.com/config`. A common issue is that it isn't, then it can't create the `config-user.php` and silently fails. See also #34."}],"action":{"name":"View Issue","url":"https://github.com/loewexy/pdnsmanager/issues/41#issuecomment-31
6485155"}}}

**Comment by mauricemeyer** [comment]
This issue was related to a parallel installation of pdnsmanager and poweradmin - in that case, when a poweradmin installation is already setup, the setup will fail as it can't create the necessary databases.

With 016183f244eb09be1711559976bbe939a783a42c, error messages for this case are now shown

**Comment by grischard** [comment]
Could I suggest using a pdnsmanagerusers table instead of doing the same as poweradmin?

**Comment by TheFatherMind** [comment]
The solution was very tedious.  With the help of one of the Devs a fresh install seemed to work.  I then had to use that database as a template and transform the existing database manually.  This took several hours but I managed to get it working.  I then just pointed the install at the old database.

**Comment by mauricemeyer** [comment]
@grischard You're absolutely right with that suggestion, this is going to be included in 2.0.
We initially didn't intend compatibility with poweradmin, but as this gets very ugly when switching to pdnsmanager, it's definitely going to be changed.
