### ISSUE TITLE
Stuck on upgrade page...

### ISSUE THREAD

**Issue by TheFatherMind** [loewexy/pdnsmanager#42]
So I tried to complete the install and it put me to the upgrade page.
Every time I do an install it puts me to the upgrade page.
I tried removing all of it and installing the stable version.. that too puts me to the upgrade page after install.
The login button after the upgrade puts me to... the upgrade page.

![2017-07-18_23-00-29](https://user-images.githubusercontent.com/11869399/28352799-54779d84-6c0d-11e7-8053-fec3724a97f6.png)

**Comment by mauricemeyer** [comment]
@TheFatherMind Are you using PHP 5.6.31 as in #29?

Could you please also check the PHP error logs and provide any messages that relate to this issue, if there are any?

**Comment by mauricemeyer** [comment]
This is resolved together with #41
