### ISSUE TITLE
Show warning when pdnsmanager tables are not empty or silently use them

### ISSUE THREAD

**Issue by mauricemeyer** [loewexy/pdnsmanager#44]
When pdnsmanager was already set up, the pdnsmanager specific tables are not empty. If this is the case, the install shoud prompt a warning.

Another possibility would be to silently use the exisiting configuration - which will work only if the name of the admin user that is specified during the installation differs from the one already set up or if they have the same password.

**Comment by loewexy** [comment]
The 2.0 installer does that.
