### ISSUE TITLE
User experience on adding domain.

### ISSUE THREAD

**Issue by chenhaw** [loewexy/pdnsmanager#46]
Hi Guys,

Is it normal when adding a domain using pdnsmanager, the page will not refresh after successfully added the domain?

**Comment by loewexy** [comment]
After you click on the add button you should be redirected to the record edit page.

**Comment by chenhaw** [comment]
@loewexy i added the record but it doesn't redirect to the edit page. when I go to the domain list, the domain is added. Any clue how can I troubleshoot this unexpected behavior?

**Comment by loewexy** [comment]
But the domain is added?

Have you tried to use another browser?

I fear the only way then would be to use the debugger in the development options to look where it goes wrong. But this would require deeper knowledge of webdevelopment on your side.

**Comment by chenhaw** [comment]
@loewexy, I tested on both Firefox and Chrome.

Upon checking on the debugger, I did see some warning and error.
For example, Error 404 for include/bootstrap/css/bootstrap.min.css.map

I download the package from, https://pdnsmanager.lmitsystems.de/files/pdns-manager-1.2.1.tar.gz. Is this normal?

**Comment by loewexy** [comment]
Yes that is totally fine, those are development files for bootstrap supporting the debugger, but you don't need them.

You should reach https://github.com/loewexy/pdnsmanager/blob/v1.2.1/js/add-domain.js#L23 in the javascript. This is called as callback from the function save data. You can also look at the request to api/add-domain.php and its result.

**Comment by chenhaw** [comment]
@loewexy, is it due to I have the manager installed in a sub directory rather than in root directory?

**Comment by loewexy** [comment]
I just tested it in a subdirectory, for me everything works as expected.

**Comment by chenhaw** [comment]
@loewexy thanks for the feedback. let me try to install a fresh copy on another virtual machine. thank you for your time.
