### ISSUE TITLE
db structure 

### ISSUE THREAD

**Issue by mandevx** [loewexy/pdnsmanager#48]
I have installed pdns version 4 and pdnsmanager both seems to have different db structure which version of pdns does pdnsmanager support . I understand pdns has some of its own tables but that is not my concern, what i am concerned about the missing tables of pdns itself in the db structure of pdnsmanager . Following are two dbs

MariaDB **[pdnsmanager]**> show tables;
+-----------------------+
| Tables_in_pdnsmanager |
+-----------------------+
| domainmetadata        |
| domains               |
| options               |
| permissions           |
| records               |
| remote                |
| user                  |
+-----------------------+

MariaDB **[powerdns]**> show tables;
+--------------------+
| Tables_in_powerdns |
+--------------------+
| comments           |
| cryptokeys         |
| domainmetadata     |
| domains            |
| options            |
| records            |
| remote             |
| supermasters       |
| tsigkeys           |
+--------------------+

**Comment by mauricemeyer** [comment]
Hey @mandevx, pdnsmanager should be compatible with any powerdns 4.X version.

pdnsmanager only installs tables which are needed to use pdnsmanager with powerdns.
None of the missing databases is essential to powerdns operation as they are needed for additional functionality:

- The `comments` table is used for comments, which are currently not supported in pdnsmanager
- The tables `cryptokeys` and `tsigkeys` are needed for DNSSEC, which is not yet supported by pdnsmanager
- The `supermasters` table is needed for operation as slave to a supermaster, which is relevant for slave zones only and is currently not supported by pdnsmanager

So, those tables all belong to functionality that pdnsmanager doesn't yet offer and are therefore omitted.

Does this answer your question well enough?

**Comment by mandevx** [comment]
@mauricemeyer Thanks for the details, so If i understand correctly, I can first instal my pdns 4 related db and then  run pdnsmanager install on same db so additional tables will be added related to pdns manager . Since both powerdns and pdnsmanager both are fresh install so I dont see it will be big problem merging both dbs since pdnsmanager needs to be on same db as powerdns.

**Comment by mauricemeyer** [comment]
@mandevx Absolutely correct, pdnsmananger only creates the pdns tables if they don't exist.

pdnsmanager itself needs the `users` and `permissions` table which it will create upon installation, but it does not interfere with an existing pdns installation at all.
