### ISSUE TITLE
pdnsmanager and letsencrypt setup 

### ISSUE THREAD

**Issue by mandevx** [loewexy/pdnsmanager#49]
I want to use pdnsmanager for letsencrypt new domain certificate generation by dns based challenge after installing pdnsmanegr now I am at part of letsencrypt and the part which explains to add domain to json and pem certificate to domain using pdnsmanager interface . what I am confused about is that which domain is this part suggesting is it for each new domains I want to add to dns and for that each new domain I need to create txt record with pem certificate as key .

would appreciate some info on this part mentioned below related to domain .

change to the directory of pdns-client, generate a keypair and output the public key:

cd pdns-client
./pdns-keygen
cat pdns.public.pem
Copy the generated public key to your clipboard.

In the next step, open a browser and login to your PDNS Manager instance. Add a record to your domain with the name _acme-challenge.<yourdomain>, type TXT and content none. Use a Priority of 0 and a TTL of 60.

Afterwards, click on to share icon which is the last icon in the row of the record. Click on Add Key. Enter a description like ACME and paste the public key from your clipboard into the field. Confirm with Add. You now need to remember the ID of the permission you have added, which is displayed in the table on the left.

Configure pdns-acme
Change to the directory of pdns-acme and copy the example config.

cd ../pdns-acme
cp pdns-acme.json.example pdns-acme.json
Open the file pdns-acme.json with an editor of your choice. In the config section adjust the path of your PDNS Manager installation and also the deploy-wait value. The deploy-wait parameter determines how long the script should wait for the DNS servers to get the right results. This value depends on your nameserver setup. The default of 300 should do well for most setups. After these changes, the section looks like that:

"config": {
        "server": "https://<yourdomain>/",
        "pdns-client": "../pdns-client/pdns-client",
        "deploy-wait": 300
    }

**Comment by mauricemeyer** [comment]
I don't fully understand your question, but as far as I understand it is regarding the Public Key authentication against the API with pdns-client?

So what you do is the following, assuming your frontend is at `https:://dns.example.com/`:

The `pdns-acme.json`-config looks like this:

``
"config": {
  "server": "https://dns.example.com/",
  "pdns-client": "../pdns-client/pdns-client",
  "deploy-wait": 300
}
``

Assume you want to get certificates for `test.example.com` and `mail.example.com`, you create the records:

- `_acme-challenge.test.example.com`, type `TXT`, TTL 60
- `_acme-challenge.mail.example.com`, type `TXT`, TTL 60

For both of those records, you add the Certificate you generated in pdns-cleint (`pdns.public.pem`) via "Add key".
You do not need multiple keys for pdns-client, but you need to add the key of the specific instance to all records that it should update.
