### ISSUE TITLE
Increase visibility of user input errors.

### ISSUE THREAD

**Issue by broedli** [loewexy/pdnsmanager#5]
Currently user input errors are handled with a red line around the erroneous field. This may confuse the user since there is no obvious response to the users action. Normally a user would probably expect a refresh of the current view after he pressed `Add`or `Delete` to get the updated content after his action was taken. A refresh doesn't happen and that is fine in my opinion. But the current red line may lead to the perception that the request was not executed, the interface stopped working, or what not because it's simply not recognized easily as a faulty input ...

A better approach would be to get "more" into the users eye and give him a better reasoning for the error. A better visible reaction to his failed action.

Take your install.php for example. A faulty mysql configuration will spawn a red bar at the top stating the error.

By the way,
happy easter and thanks for your project.

**EDIT**: Spelling

**Comment by loewexy** [comment]
Are you only referring to the edit-master.php with the inputs for adding a record. Or is this a general note. e.g. when you add a domain it is handled equally.

Maybe it would be an idea to add a tooltip from [http://getbootstrap.com/javascript/#tooltips](Bootstrap) to the respective button. Then if validation fails the erroneous inputs will be marked as now. Additionally you get a tooltip saying "Please check the marked input". Is that a solution like the one you have in mind?

**Comment by broedli** [comment]
The other instances are "better" in the way that they have text above the field which increases the visibility. But I meant this in a more general way.

**Comment by loewexy** [comment]
What do you think about the solution with a tooltip or do you have another solution in mind?

**Comment by broedli** [comment]
A tooltip could be fine.

**Comment by loewexy** [comment]
I added a visual feedback via a little shake movement. I think that should suffice.
