### ISSUE TITLE
Trailing dot added to the email address in SOA

### ISSUE THREAD

**Issue by SpaceJelly** [loewexy/pdnsmanager#51]
As title, any change to the SOA and the email has a trailing dot appended to the end causing pdnsutil check-zone to throw up a warning.

Removing the trailing dot in the database manually and pdnsutil check-zone is happy :)

**Comment by SpaceJelly** [comment]
ok, easy to fix:

in lib/soa-mail.php
second to last line change from:
`return implode(".", $parts);`
to
`return rtrim(implode(".", $parts), ".");`

Why to do this? As the SOA needs trailing dots at the end of the primary server and email address. Well, reading up and PowerDNS mysql backend it is preferred not to store the trailing dot in the database as PDNS will add it anyway, digging the domain SOA with no trailing dots clearly shows this being added.

https://doc.powerdns.com/md/types
Warning: Host names and the MNAME of a SOA records are NEVER terminated with a '.' in PowerDNS storage! If a trailing '.' is present it will inevitably cause problems, problems that may be hard to debug. Use pdnsutil check-zone to validate your zone data.

**Comment by mauricemeyer** [comment]
Thanks for the info, I will check and implement it soon.
