### ISSUE TITLE
Confirm on Delete

### ISSUE THREAD

**Issue by SpaceJelly** [loewexy/pdnsmanager#59]
Improvement request.

Can we have a confirm on Delete please. Currently deletes records without warning.

This could be a var set in the user config file so people could choose to enable/disable as required.

**Comment by mauricemeyer** [comment]
I added it to the 2.0 milestone - had this in mind, too.

**Comment by TheFatherMind** [comment]
I think the ability to toggle the confirm on.. or off... is a good idea.  I never re-think my choices.  (:

**Comment by loewexy** [comment]
2.0 has confirm screens on every deletion, be it domains, records, credentials or users.
