### ISSUE TITLE
Log files

### ISSUE THREAD

**Issue by bomart** [loewexy/pdnsmanager#60]
The only thing missing is logs who was logged and what he did.

**Comment by mauricemeyer** [comment]
This is a good idea we'll consider to add.

**Comment by SpaceJelly** [comment]
Yes, please do add! This will be a fantastic addition. Audit trails are very useful in troubleshooting.

**Comment by loewexy** [comment]
Version 2 will come with a logging subsystem with configurable verbosity. If that for whatever reason is not sufficient you can reopen this issue after the release of 2.0.
