### ISSUE TITLE
Add pdnsmanager to an existing pdns database

### ISSUE THREAD

**Issue by dtoubelis** [loewexy/pdnsmanager#64]
I have a running pdns instance with an existing pdns database. After I installed pdnsmanager 1.2.1 I pass the existing database info to pdnsmanager, it says that upgrade is required, reports success and shows login button. However, when I press the `Login` button it performs upgrade again, reports success and continues this infinite cycle.

**Comment by loewexy** [comment]
Can you check in your database if the version in the options table is increased to the current version. It should be 3 after the upgrade to 1.2.1
