### ISSUE TITLE
Upgrade Loop

### ISSUE THREAD

**Issue by iGlaedr** [loewexy/pdnsmanager#69]
Hi
I have installed powerdns with a mysql backend.

When i downloaded the pdnsmanager in the web-root and tried to use the installer it failed (i head to set the DB setting manual).

Now i have to Upgrade my db from 0V to 3V.

When i the upgrade the os i works.

<img width="593" alt="screen shot 2018-03-15 at 09 24 03" src="https://user-images.githubusercontent.com/25317853/37451723-ccc45462-2832-11e8-92e9-0f2b11e510b7.png">
<img width="525" alt="screen shot 2018-03-15 at 09 18 53" src="https://user-images.githubusercontent.com/25317853/37451730-d0cabfd8-2832-11e8-83e8-ee2a982d03aa.png">

When i press login it just brings me back to the "An upgrade for your PDNS Manager database is available and must be installed!" Page.

THX
iGlaedr

OS Debian9
Webserver NGINX (with working PHP)
DB MariaDB

**Comment by loewexy** [comment]
I assume this is the consequence of not using the installer. Therefore your database is empty and the upgrade fails as there is no present database schema. Either you get the installer to work, or you have to setup the schema by hand from the code in api/install.php.

You may verify my assumtion by checking that the database is currently empty.

**Comment by WeWin55** [comment]
Hi, i had the same problem if I used the same database as i used with powerdns previously.
You need to have a "real" pdns database before using pdnsmanager.

**Comment by iGlaedr** [comment]
I i had to add a add one DB Table and one entry:

`CREATE TABLE `options` (
  `name` varchar(255) NOT NULL,
  `value` varchar(2000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `options` (`name`, `value`) VALUES
('schema_version', '3');
`

Now it works.
