### ISSUE TITLE
[feature] use pdns http api

### ISSUE THREAD

**Issue by piwats** [loewexy/pdnsmanager#7]
Is it possible to use the pdns http api as described in 

https://doc.powerdns.com/3/httpapi/README/

to manage the records?

Advantages are being agnostic about the db backend, let pdns handle this.

**Comment by loewexy** [comment]
I am not shure weather I understand what your question is. If my answer does not suffice please ask again.

I think it should be possible to use the Powerdns API as it also updates the database. The downside is that in my understanding the Powerdns API is less powerfull. It allows only one password for the complete server not individual ones for each record. Also it does not support updating using RSA signatures. Lastly an update uses POST requests which is not feasible if you want to have a dynamic DNS update from a router like the FritzBox.

The advantage of beeing agnostic about the backend is not a real one, as PDNS Manager relies on the MySQL Database for its own Data and will not run without it. So if you want to use PDNS Manger currently you are required to use the MySQL backend.
