### ISSUE TITLE
Centos 7 and pdnsmanager version 2

### ISSUE THREAD

**Issue by santxus** [loewexy/pdnsmanager#70]
Hi guys

First thank you for your job.

I have already installed and working pdnsmanager on CentOS 7, if you want i can create a manual with the steps.

Second thing, if the version 2.0 in progress or is abandoned ?

Thank you

**Comment by robetus** [comment]
Hi @santxus I'm having trouble with the /var/www/html permissions with apache in Centos 7. I can't connect to the database, what did you use for the permissions for your pdnsmanager folder?

**Comment by robetus** [comment]
I figured out, and for anyone else who wants to use Centos 7 and apache it's:

```
chown -R apache: /var/www/pdnsmanager
chmod g=u -R /var/www/pdnsmanager
```
It is possible that you can just run the second command and not change the owner, but I did both and it worked.
