### ISSUE TITLE
Install not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by robetus** [loewexy/pdnsmanager#71]
I know this issue has been posted before with no real resolution so I'm posting the same issue with a different result. When I click the install button in firefox on macOS I get the following error in the console:

```
XML Parsing Error: unclosed token
Location: https://mydomain.com/api/install.php
Line Number 1, Column 1:
```
I get the following in red when I view the source in the browser:
<img width="577" alt="screen shot 2018-03-26 at 10 21 53 am" src="https://user-images.githubusercontent.com/8278397/37894762-8e42d1b8-30df-11e8-8d7e-fcaa33102ff9.png">
<img width="500" alt="screen shot 2018-03-26 at 10 21 43 am" src="https://user-images.githubusercontent.com/8278397/37894763-8e5c65a6-30df-11e8-9ddb-025718bf00ca.png">

Did anyone actually find a solution to this? Or should I move on? I'm using v1.2.1 and I tried to install without pdns installed first and then I tried it with pdns installed. Any ideas would be appreciated.

**Comment by loewexy** [comment]
You should use an empty database for the installation. Any existent tables will make the installation fail.

And in the browser you should never get PHP code, are you shure that php is enabled in your webserver?

If none of that is the case, go to the devolper menu bar, open the network tab and post the complete request, this includes headers, parameters and response.

**Comment by robetus** [comment]
I have php 7.0 installed for sure, but yes in the source view in the developer menu bar I can see the php code. Does it matter where I put the pdnsmanager files? I've put them in the /var/www/html location as well as the home directory of the user with the exact same result.

In the network tab I see that install.php gives a 200 code which is OK, but still nothing happens when I click the button.

**Comment by loewexy** [comment]
Yea obviously you do not execute PHP code which is a problem... what is your setup? Can you crate a test.php in your document root with the following content and then call it with your.url/test.php

```
<?php

phpinfo();
```

**Comment by robetus** [comment]
Wow, I guess I didn't have php installed even though I tested it via ssh and it seemed to be working. I guess I needed apt-get install php, installed everything else but not just php. Thanks for pointing me in the right direction.
