### ISSUE TITLE
supermasters table missing

### ISSUE THREAD

**Issue by robetus** [loewexy/pdnsmanager#72]
I'm getting an error when I check the status of powerdns. It shows that it is running but there are errors. I don't think pndsmanager will work correctly with this error:

```
gmysql Connection failed: Could not prepare statement: select account from supermasters where ip=? and nameserver=?: Table 'pdnsmanager.supermasters' doesn't exist
Caught an exception instantiating a backend: Unable to launch gmysql connection: Could not prepare statement: select account from supermasters where ip=? and nameserver=?: Table pdnsmanager.supermasters' doesn't exist
```

The table supermasters does exist in both the pdns and pdsmanager database. There is suppose to be a separate database for each pdns and pdnsmanager correct, or are they both suppose to be inside of one database?

**Comment by loewexy** [comment]
Did you follow the instructions on the website? From there it should be clear that Powerdns and Pdnsmanager will use the same database. Also the provided Powerdns config there does not enable supermaster operation, therefore your error should not be there.

**Comment by robetus** [comment]
Thanks for the reply but you do know that pdnsmanager does not create the supermaster table right? It actually leaves out a couple tables that are necessary to do a master slave setup, but I'm guessing you didn't write the code thinking that someone wanted to do a master slave sync. 

I am successfully using pdnsmanager and pdns from the same database, which may or may not have been your intention.

I have attached an empty database you can implement if you want. This database holds all the tables for someone to be able to master/slave pdns plus everything else of course.

[pdns.sql.zip](https://github.com/loewexy/pdnsmanager/files/1855858/pdns.sql.zip)

**Comment by loewexy** [comment]
The current version of powerdns supports (as stated in the documentation) only master and native zones. Slave operation is currently not supported, therefore the tables are not required. If you configure it like in the tutorial it works fine with the stated functionality.

Notwithstanding the above, PDNSManager 2.0 will likely support slave operation. Superslave operation however will definitely not in the 2.0 release.

**Comment by robetus** [comment]
I'm using PowerDNS 4.1.1 with pdnsmanager on a master and attached slave and they are syncing just fine. If you mean it's not supported in the GUI, then I understand. This would be a nice feature. With pdns once you declare a slave and a sync time in the conf file they will sync, pdnsmanager doesn't need to be compatible with it, it just works.

A supermaster is just the master that all the slaves sync to, so whenever there is a database entry in the supermaster if a slave is attached it and the DNS checks out the slave will sync to it automatically. It's actually very easy to setup by just inserting the needed tables into the databases and declaring a supermaster in the slave database and the AXFR entires in the master conf file.

I'll probably add a couple more slaves in other places in the world for more coverage at a later time.
