### ISSUE TITLE
centos 6.8 nginx + php-fpm error

### ISSUE THREAD

**Issue by Nurlan199206** [loewexy/pdnsmanager#73]
Hi.

i cant even install, i am getting errors like that.

my PHP version:

`PHP 7.1.16 (cli) (built: Mar 28 2018 13:34:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.16, Copyright (c) 1999-2018, by Zend Technologies
`

`thrown in /var/www/html/pa/api/install.php on line 126" while reading response header from upstream, client: 37.99.32.90, server: myserver, request: "POST /pa/api/install.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "myserver", referrer:`

**Comment by loewexy** [comment]
That seems to be an error with the PHP Setup on nginx. I have no experience there, so unfortunately I have no idea what could go wrong there. The line it complains looks fine in the sourcecode.

What you posted is only part of the error message, the exception is not shown here. You can try to post the complete error, maybe this is more insightful.

**Comment by Nurlan199206** [comment]
![pdns mgr](https://user-images.githubusercontent.com/22808731/38191821-f670c784-368b-11e8-908a-6601eb455613.PNG)

config directory permissions: `drwxrwxr-x 2 root root  4096 Apr  2 15:25 config`


```
2018/04/02 15:17:55 [error] 8850#0: *314 FastCGI sent in stderr: "PHP message: PHP Warning:  include(config-user.php): failed to open stream: No such file or directory in /var/www/html/pa/config/config-default.php on line 33
PHP message: PHP Warning:  include(): Failed opening 'config-user.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/pa/config/config-default.php on line 33" while reading response header from upstream, client:
```

**Comment by mauricemeyer** [comment]
As the error says, the config directory permissions are incorrect.

Your config directory is owned by root:root, so the web server cannot
write to it. Please adjust the owner and group to the one of the web
server.
On April 2, 2018 11:39:44 AM GMT+02:00, Nurlan199206 <notifications@git
hub.com> wrote:

**Comment by Nurlan199206** [comment]
@mauricemeyer 

```
total 120
-rw-r--r-- 1 nginx nginx  4937 Apr  2 15:43 add-domain.php
drwxr-xr-x 2 nginx nginx  4096 Apr  2 15:43 api
drwxr-xr-x 2 nginx nginx  4096 Apr  2 15:43 config
-rw-r--r-- 1 nginx nginx  5565 Apr  2 15:43 domains.php
-rw-r--r-- 1 nginx nginx  9172 Apr  2 15:43 edit-master.php
-rw-r--r-- 1 nginx nginx  5823 Apr  2 15:43 edit-remote.php
-rw-r--r-- 1 nginx nginx  4653 Apr  2 15:43 edit-user.php
drwxr-xr-x 4 nginx nginx  4096 Apr  2 15:43 include
-rw-r--r-- 1 nginx nginx  2888 Apr  2 15:43 index.php
-rw-r--r-- 1 nginx nginx  5227 Apr  2 15:43 install.php
drwxr-xr-x 2 nginx nginx  4096 Apr  2 15:43 js
drwxr-xr-x 2 nginx nginx  4096 Apr  2 15:43 lib
-rw-r--r-- 1 nginx nginx 11344 Apr  2 15:43 LICENSE
-rw-r--r-- 1 nginx nginx  1960 Apr  2 15:43 logout.php
-rwxr-xr-x 1 nginx nginx   162 Apr  2 15:43 make-release.sh
drwxr-xr-x 2 nginx nginx  4096 Apr  2 15:43 nbproject
-rw-r--r-- 1 nginx nginx  3277 Apr  2 15:43 password.php
-rw-r--r-- 1 nginx nginx  1140 Apr  2 15:43 README.md
-rw-r--r-- 1 nginx nginx  2582 Apr  2 15:43 upgrade.php
-rw-r--r-- 1 nginx nginx  4878 Apr  2 15:43 users.php

```

still

`Can't write to the config directory, please check the file system permissions`

**Comment by Nurlan199206** [comment]
i given recursive permissions to web root directory.

**Comment by Nurlan199206** [comment]
@mauricemeyer finally installed.

but now xD

`PHP message: PHP Warning:  include(): Failed opening 'config-user.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/pa/config/config-default.php on line 33" while reading response header from upstream, client`

searching solution

**Comment by mauricemeyer** [comment]
Please verify that php-fpm (I assume from the first post) is running as the nginx user, too. If the `config-user.php` file is not generated, that points to an error generating that file.

Please always attach the relevant lines from your PHP error log for such problems as well as any browser console errors, if present.
