### ISSUE TITLE
Default sql request optimization for large database.

### ISSUE THREAD

**Issue by mathieu-nfrance** [loewexy/pdnsmanager#76]
Hi,

We have tested pdns-manager with 70000 domain names and 900000 entries and response times were too long : more than 12 seconds for the first page and on each search. Our developer make a modification on the main sql request and response time fell below 2 seconds. Here is the modification:

in api/domains.php:

    // Now the real search is done on the database
    /*
    $sql = "
        SELECT D.id,D.name,D.type,count(R.domain_id) AS records
        FROM domains D
        LEFT OUTER JOIN records R ON D.id = R.domain_id
        LEFT OUTER JOIN permissions P ON D.id = P.domain
        WHERE (P.user=? OR ?)
        GROUP BY D.id, D.name, D.type
        HAVING
        (D.name LIKE ? OR ?) AND
        (D.type=? OR ?)
    ";
    */

    $sql = "
        SELECT D.id,D.name,D.type,(select count(R.domain_id) FROM records R WHERE D.id = R.domain_id) as records
        FROM domains D
        LEFT OUTER JOIN permissions P ON D.id = P.domain
        WHERE (P.user=? OR ?)
        GROUP BY D.id, D.name, D.type
        HAVING
        (D.name LIKE ? OR ?) AND
        (D.type=? OR ?)
    ";

I will make push requests myself when I will be fluent in git, but not today :)

Have a nice day,
Mathieu.

**Comment by loewexy** [comment]
Thank you for your contribution. As I am currently in the process for releasing the all new version 2 of PDNS manager, i won't change anything in version 1.x. But I would welcome your contribution again if it is still a problem in version 2.0.
