### ISSUE TITLE
Connection to database failed Error

### ISSUE THREAD

**Issue by c0fe** [loewexy/pdnsmanager#8]
I keep getting this error: Connection to database failed

I have MariaDB 10 installed on Ubuntu 14.04

I followed this guide to install PowerDNS:

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-powerdns-with-a-mariadb-backend-on-ubuntu-14-04

So I am not sure what I can possibly be doing wrong. I have created another database as well but still same error.

**Comment by loewexy** [comment]
PDNS Manager will create its own database structure, so it is better if you create a empty one for it.

Can you provide the PHP error log of the installation? Have you checked you have all dependencies installed notably php5-mysqlnd.

**Comment by c0fe** [comment]
Googling it seems that the log would be stored in: /var/log/httpd/php_error_log but that file is blank. I have created an empty database and still same error message.

**Comment by c0fe** [comment]
I think I found it: http://hastebin.com/biqajobijo.coffee

**Comment by loewexy** [comment]
According to the log you tried it using the mysql user root with no password. Are you able to login on the shel with *mysql -uroot* ? It seems to be a problem with your credentials.

**Comment by c0fe** [comment]
I have tried mysql with no root password but i don't really like that idea for security reasons. I am able to login in via shell.

**Comment by c0fe** [comment]
I should mention I tested the credentials idea by punching a bunch of gibberish and I got another error that access was denied.

**Comment by loewexy** [comment]
According to your log you did not supply a password to the installer, so it tries to connect as root with no password to the database. Of a security perspective this would be fatal. If the above command works with only mysql -uroot then your mysql server is configured without root password. So please make shure that your credentials are valid. The information you give is inconsistent.

**Comment by c0fe** [comment]
I will make a screencast then of this, I mean I am not insane.

**Comment by loewexy** [comment]
I tested the installation with the current version using ubuntu 14.04 half a hour ago. Also your provided log says that the installer is trying to use no password and the user root: *Access denied for user '**root**'@'localhost' (using password: **NO**)*

As a general recommendation you should not use root as the user for PDNS Manager. Instead create a new one with access to its own database. Also assign strong passwords to all users (root and the one for pdns manager). You can test your configuration on the shell using *mysql -uusername -ppassword*

**Comment by c0fe** [comment]
Well now I got a completely different problem not even sure:

https://www.youtube.com/watch?v=T_dPyCgF2vI&feature=youtu.be&hd=1

**Comment by loewexy** [comment]
Okay well that seems to be a different problem. Either this is a bug in the installer of PDNS Manager, or a problem in your client. Which browser and version are you using? Do you use Addons like NoScript? If you have a second browser installed you can try with that one. I would then be also intressted which browser in which version you tried.

**Comment by c0fe** [comment]
I have tried both Chrome and Firefox I have no plugins at all.

**Comment by mauricemeyer** [comment]
Please open the Installer in Firefox and open the network tab of the developer console. (F12)
Fill out the form and klick on the "Install" button. There should be requests popping up now. Right click any of them and use the "Save as HAR" button to save all requests and the responses. 
Please note that all passwords are available in clear text in this log.

Paste this log on pastebin or somewhere else and provide us with the link, thank you.
