### ISSUE TITLE
Nginx config

### ISSUE THREAD

**Issue by joltcan** [loewexy/pdnsmanager#81]
Hello guys!

This is more of a whish than anything else, would it be possible to get a working nginx example for the setup. I've tried multiple Slim-related examples but cant get it to work, (the API never responds to my curl requests).

Here is what I've tried with
```
    location ~ ^/api/(.*) {
        alias /home/pdnsmanager/backend/public;
        try_files $1 $1/ @php;
        index index.php;
    }

    location / {
        root /home/pdnsmanager/frontend;
    }

    location @php {
       fastcgi_split_path_info ^(/api)(/.*)$;
       fastcgi_pass     unix:/var/run/php/fpm-pdnsmanager.sock;
       fastcgi_index    index.php;
       include          fastcgi_params;
       fastcgi_param    SCRIPT_FILENAME $request_filename;
       fastcgi_param    REQUEST_URI $fastcgi_path_info;
       fastcgi_read_timeout 900;
    }
```

**Comment by mauricemeyer** [comment]
@joltcan Can you please elaborate on:

> the API never responds to my curl requests

Does it time out, reject, give you something you don’t expect? At best, please provide some requests you tried and the nginx access and error logs for the relevant timeframe as well as the fpm logs.

To see if you’re landing in the correct location, you can try e.g. [adding a header for debugging](https://stackoverflow.com/questions/12703702/nginx-test-which-location-used-to-process-request).

**Comment by joltcan** [comment]
So, I continued a bit today to kind of match the apache rewriting:
```
    root /home/pdnsmanager/backend/public;

    location / {
        root /home/pdnsmanager/frontend;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        try_files $uri $uri/ /index.php;
    }

    location ~* \.php$ {
        if ($request_uri ~* "/api(.*)") {
            set $req $1;
        }
        fastcgi_split_path_info ^(/api)(/.*)$;
        fastcgi_pass     unix:/var/run/php/fpm-pdnsmanager.sock;
        include          fastcgi_params;
        fastcgi_param    SCRIPT_FILENAME $request_filename;
        fastcgi_param    REQUEST_URI $req;
        fastcgi_read_timeout 900;
    }
```


In this case it works with /setup, it creates the database (verified in mysql), but I can't login, and looking at the inspector I see that a POST to /api/v1/sessions fails with 500, and a GET to /api/v1/sessions fails with 404.

No errors in the nginx error log(except the 404/500), but the PHP log complaints:
`
[26-Oct-2018 17:01:56 Europe/Berlin] PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/pdnsmanager-v2.0.1/backend/services/Database.php on line 72
`
If I go/curl to the page, there is no output back, only another PHP unexpected '?' as above.

**Comment by loewexy** [comment]
This looks like you use a PHP version prior to 7.1 which does not support optional variables with types. Please make sure to use at least PHP 7.1.

**Comment by joltcan** [comment]
Turns out I use the Debian defaults, which is 7.0. Thanks for helping out!

**Comment by loewexy** [comment]
If you have a working configuration now, it would be nice if you could make a pull request to add instructions for Nginx to the website. The repo is [here](https://github.com/loewexy/pdns-manager-website).

**Comment by joltcan** [comment]
I would if I had, but I'm still going strong with Debian stable on that server. Ill see if I might get around to dockerify it later.

**Comment by ToeiRei** [comment]
@joltcan I got your config running so far. Maybe I can help on debugging?

**Comment by msg7086** [comment]
Used @joltcan configuration, working fine for me.

This is what I wrote.

```
server {
    listen 80;
    server_name ns1.o.o;

    root /var/www/pdnsm/backend/public;

    location / {
        root /var/www/pdnsm/frontend;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        try_files $uri $uri/ /index.php;
    }

    location ~* \.php$ {
        if ($request_uri ~* "/api(.*)") {
            set $req $1;
        }
        fastcgi_split_path_info ^(/api)(/.*)$;
        fastcgi_pass     unix:/var/run/php/php7.3-fpm.sock;
        include          fastcgi_params;
        fastcgi_param    SCRIPT_FILENAME $request_filename;
        fastcgi_param    REQUEST_URI $req;
        fastcgi_read_timeout 900;
    }
}
```

**Comment by theel0ja** [comment]
I think Nginx configuration should be added to the website.

**Comment by DesktopMasters** [comment]
Where on the website was this added I cannot find it.  I am concerned that this information as still current and oh so lucky I was able to find it here.

**Comment by joltcan** [comment]
> 
> 
> Where on the website was this added I cannot find it. I am concerned that this information as still current and oh so lucky I was able to find it here.

It doesn't seem to be added in the documentation, but copy them from two comments up from yours.

**Comment by DesktopMasters** [comment]
Can we please honor this guys efforts by getting it on the website for techs like me who have evolved from apache to nginx please.  Or at the very LEAST use the web superpower and drop a little hyperlinked comment in the official directions telling people to come to this post if they are setting up with NGiNX please.

**Comment by joltcan** [comment]
I made a pull request to add it to the docs today!


--
Fredrik Lundhag
Signal: +46 709 576 009

**Comment by DesktopMasters** [comment]
@joltcan You are awesome.  FYI your posted config worked perfectly for me!  Saved me hours of work or possibly even avoided complete failure as I would have never figured this out on my own.  I am now running PDNS Manager through an NGiNX container thanks to you.

**Comment by joltcan** [comment]
Glad to hear it! 


--
Fredrik Lundhag
Signal: +46 709 576 009

**Comment by loewexy** [comment]
Thanks for you pull request I have merged it and the documentation should be online.
