### ISSUE TITLE
The application has already been setup or the backend is misconfigured.

### ISSUE THREAD

**Issue by timoanttila** [loewexy/pdnsmanager#82]
We have been using poweradmin few years now, but it does not support newest PHP + mcrypt anymore so we're looking for alternative Web GUI.

I tried to install PDNS Manager but it always says "The application has already been set up or the backend is misconfigured." followed the guide from https://pdnsmanager.org/quickstart/.

Looks like installation is working on another server which is not PowerDNS server. But after creating a user the password is not working and I am typing it right. However, it created all the necessary tables and user information (with wrong password).

What should I do?

**Comment by loewexy** [comment]
Is the database you use empty?

**Comment by tewdin** [comment]
I tried to install to the existing database (because we have a lot of domains) and then empty one, but the installation progress did not even go that far in our main server. It stopped before even started. And there is a different error when the table is not empty. Secondary server was ok until I tried to log in.

**Comment by loewexy** [comment]
It is only supported to install pdnsmanager to an empty database, the setup should throw an error on non empty databases. If you want to transfer domain data, you can do this manually after setup on the SQL level.

**Comment by hinch** [comment]
I'm getting the exact same message from the setup script only this is on a vm that is brand new and has nothing installed on it apart from pdns reqs etc the mysql database is created and empty but it will not let me proceed

**Comment by syntaxys** [comment]
Same here. After a clean install I can't login with the credentials used in the setup routine

**Comment by atwebm** [comment]
I had the Same Problem, when i had an Error in the Path between the Alias and the Directory-Directive.
The same also occurs, when there is a missing "Require all granted" in all Directory-Directives (the one for the Backend-API and an additional one for the Frontend).

**Comment by satishdotpatel** [comment]
I have having same error with fresh install, anyone know how to fix this error?

**Comment by loewexy** [comment]
This is duplicate with #106
