### ISSUE TITLE
[Feature Request]: Plugin for PostgreSQL

### ISSUE THREAD

**Issue by Balthyr** [loewexy/pdnsmanager#84]
Hello loewexy,

Your PDNS Manager is a very great tool. 

It would be nice if you develop and integrate a Plugin for the official PostgreSQL Backend of PowerDNS.

Thanks in advance!

Kind regards

Phil

**Comment by loewexy** [comment]
Since pdnsmanager 2.0 is using php pdo this could work theoretically out of the box. But I have no experience working with Postgres and currently I also have no time to do this. But if you want to build support for it, I will support you and would be happy to merge support.

**Comment by Balthyr** [comment]
Hi Lukas,

sehe gerade, dass ich auch auf Deutsch mit dir weiter schreiben kann.

Ich würde dir gerne Unterstützung leisten das PlugIn für Postgres zu schreiben.

LG

**Comment by loewexy** [comment]
Sorry I did not see your Message here. If you are still interested you can contact me via mail for additional support.

Please use English in the issue tracker on github so that the messages are readable for everyone.

**Comment by Balthyr** [comment]
Thank you for your reply. I will contact you via mail

**Comment by genofire** [comment]
a good startingpoint could be #102 i use and run it over severy years now
