### ISSUE TITLE
Docker image returns "Page not found"

### ISSUE THREAD

**Issue by EugenMayer** [loewexy/pdnsmanager#85]

**Comment by loewexy** [comment]
I do not maintain a docker image. And the one I have found seems to use outdated versions. Please file the bug there.

**Comment by EugenMayer** [comment]
please delete that issue it was created accidently. i did though properly package your app into a docker container though https://github.com/EugenMayer/docker-powerdns/tree/master/pdnsmanager .. if you are in any way interested
