### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot read property 'total' of undefined

### ISSUE THREAD

**Issue by fmondini** [loewexy/pdnsmanager#88]
After a successful login nothing is shown and in the chrome console there is an error:

`Uncaught (in promise): TypeError: Cannot read property 'total' of undefined`

Please help...

**Comment by Speedy059** [comment]
I have the same issue. Any ideas on what would be causing this?

**Comment by wmtech-1** [comment]
If setup fails silently, you can login with any data and the screen is empty because the database is empty. Since no data can be read you get this error.

The underlying problem is that setup failed silently. 

Do you perhaps use a CentOS machine?

**Comment by Eiskaltereistee** [comment]
Same issue. And yes, I am using a centos box. Can you help? @wmtech-1

**Comment by Speedy059** [comment]
I installed the pdns using the mariadb packages and it worked. Using MySQL doesn't, too many packages missing and was a pain trying to figure out which ones were needed.

**Comment by Eiskaltereistee** [comment]
I think no tables are created by pdnsmanager after setup.. I try to make the installation manaual and try again then

**Comment by wmtech-1** [comment]
It seems this product is unsupported unfortunately.

It cannot be installed at CentOS 7 machines. Debian works.
