### ISSUE TITLE
Let's Encrypt "Challenge in invalid!"

### ISSUE THREAD

**Issue by Yamakasi** [loewexy/pdnsmanager#93]
Using the docs and a resolvable TXT record which is empty I get the following:

`ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "dns-01",
  "status": "invalid",
  "error": {
    "type": "urn:ietf:params:acme:error:unauthorized",
    "detail": "Incorrect TXT record \"none\" found at _acme-challenge.my.domain",
    "status": 403
  },
  "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/UjvirLyQRDcisSLtHP-h5qvdJ_1UNgbsmfiVfKadsvY/12691864631",
  "token": "z9hnqaUx0ArhctXunKqkfLhA8qF8ZOpfy9My8-3M8Dw"
})`

What goes wrong here ? Any help/info ?

**Comment by loewexy** [comment]
`curl -s https://yourserver.org/api/v1/remote/servertime` should return a unix timestamp as JSON. Check if this is the case.

**Comment by Yamakasi** [comment]
> /api/v1/remote/servertime

Nope doesn't return anything

**Comment by loewexy** [comment]
You then have a problem with the pdnsmanager setup. Is the GUI working? And which version of pdnsmanager do you use?

**Comment by Yamakasi** [comment]
> 
> 
> You then have a problem with the pdnsmanager setup. Is the GUI working? And which version of pdnsmanager do you use?

Yes working fine! Latest version 2.0.1

**Comment by loewexy** [comment]
I have no idea what your problem could be, if the responds to every other query...
