### ISSUE TITLE
Update Documentation - Requirments(php-json)

### ISSUE THREAD

**Issue by megabert** [loewexy/pdnsmanager#94]
Documentation/Website says nothing about a requirement of "json". Please add a note to the requirements. that php-json is needed. 

I got the errormessage:

`Error\nMessage: Call to undefined function Slim\\Http\\json_decode()\n`

which went away after installing php7-json.

**Comment by loewexy** [comment]
It was installed by default for me. But I added it to the quickstart manual along with the php apcu extension.
