### ISSUE TITLE
DB-Schema incompatibility of pdnsmanager with powerdns

### ISSUE THREAD

**Issue by megabert** [loewexy/pdnsmanager#98]
I have currently tried to manually extend my powerdns-schema with the additional tables needed for pdns manager. I reviewed the sql files in backend/src/sql from the source and took the statements needed to extend the pdns schema, keeping the existing tables and data.

When I applied the different sql commands I got an error at this statement:

```ALTER TABLE `remote`
    ->   ADD CONSTRAINT `remote_ibfk_1` FOREIGN KEY (`record`) REFERENCES `records` (`id`) ON DELETE CASCADE;```

The error is:

```ERROR 1005 (HY000): Can't create table `pdns`.`#sql-f_31fd` (errno: 150 "Foreign key constraint is incorrectly formed")```

Searching for the error message brought up the cause that the data types of the columns _remote_.record and _records_.id are different: 
- PowerDNS: _records_.id **bigint**
- pdnsmanager: _remote_.record **int**

My fix is to change the data type of the pdnsmanager-table _remote_ to bigint:

```ALTER TABLE remote MODIFY record BIGINT```

**Comment by loewexy** [comment]
Okay I see the difference here. I do not see a severe problem here, but since the fix should not be that hard I will implement it.
