### ISSUE TITLE
Ability to edit dns entries for SLAVE domains

### ISSUE THREAD

**Issue by sriccio** [loewexy/pdnsmanager#99]
Hello,

I understand that a SLAVE zone should not need to be edited but instead be edited on the MASTER of the zone.

However in our setup, having multiple non-public backend powerdns supermasters which are provisioning a pool (mysql replicated) of public front DNS, we would like to be able to edit a SLAVE zone on the front pool in case of emergency if our backend MASTER servers are temp. down.

I'm not sure that I'm clear enough, TLDR: it would be nice to be able to also edit slave zones :)

Maybe this could be an option of pdnsmanger (allow_slave_edit=0/1).

Cheers

**Comment by megabert** [comment]
One option may be to just set up a second instance of pdnsmanager pointing to the backup-server database. Should be pretty simple. In case that are multiple servers, that maybe extra work to edit zones on all not-replicated slaves.

**Comment by sriccio** [comment]
Yes indeed, that's not really the problem. The problem is that with pdnsmanager you can't edit entries of a zone of type SLAVE. Only MASTER or NATIVE.

The edit screen of a type SLAVE zone let you only change the master IP address.

**Comment by megabert** [comment]
Since you are using mysql-replication I wonder why your zones are not set to native. 

As far as I understand Master/Slave is only needed in case PowerDNS takes care of the replication itself.

**Comment by sriccio** [comment]
Our setup is a bit more complicated than that.

We have some backend master dns servers for different services that uses different kind of nameservers (bind, powerdns, windows dns servers) and that are not publicly reachable.

Then we have front end (public) dns servers that are publicly reachable, they are "superslaves" of the backend dns servers.

The front end dns server pools consiste of a  primary server that receives notify from the backend servers (supermasters) and auto populate zones as SLAVE zones and the other front end are mysql replicated.

Hard to explain without a drawing :)

But that's not really the question for this issue I opened. It would be nice to be able to edit a zone content even if they are configured as SLAVE.

For exemple powerdns-admin allows this.

As said it's only in case of emergency if the backend servers have a problem and we need to apply changes on a zone on the front end servers.

Cheers

**Comment by loewexy** [comment]
I guess for emergency cases just edit the database. I can not see any valid use for this. Furthermore I guess this will confuse any sensible user.
